// ─── Transport Types ───
export interface Transport {
  ID: string;
  trNumber: string;
  trDescription: string;
  workType: string | null;
  snowTicket: string | null;
  veevaCCNumber: string | null;
  trOwner: string;
  ownerFullName: string;
  trStatus: string;
  trFunction: string;
  currentSystem: 'DEV' | 'QAS' | 'PRD';
  importRC: number | null;
  assignedBy: string | null;
  assignedDate: string | null;
  createdDate: string;
  lastSynced: string;
  workItem_ID: string | null;
  projectName?: string;
  version: number;
}

// ─── Work Item Types ───
export interface WorkItem {
  ID: string;
  workItemName: string;
  projectCode: string;
  workItemType: string;
  snowTicket: string;
  veevaCCNumber: string;
  amsTicket?: string | null;
  businessOwner: string;
  systemOwner: string;
  leadDeveloper: string;
  functionalLead: string;
  qaLead: string;
  kickoffDate: string | null;
  devCompleteDate: string | null;
  uatStartDate: string | null;
  uatSignoffDate: string | null;
  goLiveDate: string | null;
  hypercareEndDate: string | null;
  actualGoLiveDate: string | null;
  sapModule: string;
  sapSystems: string;
  estimatedTRCount: number;
  complexity: string;
  priority: string;
  status: string;
  currentPhase: string;
  overallRAG: 'GREEN' | 'AMBER' | 'RED' | undefined;
  riskScore: number;
  deploymentPct: number;
  notes: string;
  sharepointSync: boolean;
  sharepointUrl?: string | null;
  lastSynced: string;
  application?: string | null;
  methodology?: string | null;
  uatStatus?: string | null;
  testPassed?: number | null;
  testFailed?: number | null;
  testBlocked?: number | null;
  testTBD?: number | null;
  testSkipped?: number | null;
  testTotal?: number | null;
  testCompletionPct?: number | null;
  transports?: Transport[];
  milestones?: Milestone[];
}

// ─── Milestone Types ───
export interface Milestone {
  ID: string;
  workItem_ID: string;
  milestoneName: string;
  milestoneDate: string;
  milestoneOrder: number;
  status: 'Pending' | 'Complete' | 'Overdue';
  completedDate: string | null;
  autoGenerated: boolean;
  evidence: string;
}

// ─── Dashboard Summary ───
export interface DashboardSummary {
  activeProjects: number;
  totalTransports: number;
  unassignedCount: number;
  pendingItems: number;
  completedThisWeek: number;
  stuckTransports: number;
  failedImports: number;
  avgDeploymentDays: number;
}

// ─── Pipeline Summary ───
export interface PipelineSummary {
  devCount: number;
  qasCount: number;
  prdCount: number;
  queueCount: number;
  stuckCount: number;
  failedCount: number;
}

// ─── Health Status ───
export interface HealthStatus {
  status: string;
  database: string;
  rfc: string;
  sharepoint: string;
  timestamp: string;
}

// ─── Notification ───
export interface Notification {
  ID: string;
  userEmail: string;
  type: string;
  message: string;
  trNumber: string;
  isRead: boolean;
  createdAt: string;
}

// ─── User Roles ───
export type UserRole = 'Executive' | 'Manager' | 'Developer';

export interface UserInfo {
  email: string;
  name: string;
  roles: UserRole[];
}

// ─── API Response Wrappers ───
export interface ODataResponse<T> {
  value: T[];
}

export interface ActionResult {
  success: boolean;
  message: string;
}

export interface CategorizeResult extends ActionResult {}

export interface BulkCategorizeResult extends ActionResult {
  count: number;
}

export interface RefreshResult extends ActionResult {
  recordsFetched?: number;
  recordsSynced?: number;
}

export interface ReportResult extends ActionResult {
  report: string | null;
}

// ─── SyncLog ───
export interface SyncLog {
  ID: string;
  source: 'RFC' | 'SHAREPOINT' | 'CLAUDE';
  startedAt: string;
  completedAt: string;
  status: 'SUCCESS' | 'FAILED' | 'PARTIAL' | 'IN_PROGRESS';
  recordsFetched: number;
  recordsUpdated: number;
  errorMessage: string | null;
  durationMs: number;
}

// ─── AppConfig ───
export interface AppConfig {
  configKey: string;
  configValue: string;
  description: string;
}

// ─── ReportTemplate ───
export interface ReportTemplate {
  ID: string;
  templateName: string;
  description: string;
  templateHtml: string;
  scope: 'single' | 'multi' | 'both';
  visibility: 'private' | 'public';
  isDefault: boolean;
  ownerEmail: string;
  sourceType: 'manual' | 'ai-generated';
  createdAt: string;
}

// ─── WeeklyDigest ───
export interface WeeklyDigest {
  ID: string;
  weekLabel: string;
  application: string;
  digestHtml: string;
  digestText: string;
  projectCount: number;
  riskCount: number;
  highlights: string;
  generatedBy: string;
  aiProvider: string;
  createdAt: string;
}

// ─── Test Status Result ───
export interface TestStatusResult extends ActionResult {
  testCompletionPct: number;
  uatStatus: string;
  ragImpact: 'GREEN' | 'AMBER' | 'RED';
}

// ─── AI Action Results ───
export interface AIChatResult {
  success: boolean;
  answer: string;
  provider: string;
}

export interface AIAnalyzeResult {
  success: boolean;
  proposals: string;   // JSON string of Proposal[]
  summary: string;
  message?: string;
  provider: string;
}

export interface AITemplateResult {
  success: boolean;
  templateHtml: string;
  message: string;
  provider: string;
}

export interface AIDigestResult {
  success: boolean;
  digestId: string;
  digestHtml: string;
  message: string;
  provider: string;
}

export interface AIRiskResult {
  success: boolean;
  risks: string;        // JSON string
  generated: number;
  message: string;
  provider: string;
}

// ─── SharePoint Document ───
export interface SPDocument {
  id: string;
  name: string;
  type: 'file' | 'folder';
  size: number;
  lastModified: string;
  webUrl: string;
  mimeType: string;
}

// ─── Methodology Template ───
export interface MethodologyTemplate {
  name: string;
  phases: string[];
  description: string;
}

// ─── Create/Delete Work Item results ───
export interface CreateWorkItemResult extends ActionResult {
  workItemId: string;
}

export interface AutoDetectResult extends ActionResult {
  phase: string;
}

export interface AutoLinkResult extends ActionResult {
  linked: number;
}
