// ─── Transport Types ───
export interface Transport {
  ID: string;
  trNumber: string;
  trDescription: string;
  workType: string | null;
  snowTicket: string | null;
  veevaCCNumber: string | null;
  trOwner: string;
  ownerFullName: string;
  trStatus: string;
  trFunction: string;
  currentSystem: 'DEV' | 'QAS' | 'PRD';
  importRC: number | null;
  assignedBy: string | null;
  assignedDate: string | null;
  createdDate: string;
  lastSynced: string;
  workItem_ID: string | null;
  projectName?: string;
  version: number;
}

// ─── Work Item Types ───
export interface WorkItem {
  ID: string;
  workItemName: string;
  projectCode: string;
  workItemType: string;
  snowTicket: string;
  veevaCCNumber: string;
  businessOwner: string;
  systemOwner: string;
  leadDeveloper: string;
  functionalLead: string;
  qaLead: string;
  kickoffDate: string | null;
  devCompleteDate: string | null;
  uatStartDate: string | null;
  uatSignoffDate: string | null;
  goLiveDate: string | null;
  hypercareEndDate: string | null;
  actualGoLiveDate: string | null;
  sapModule: string;
  sapSystems: string;
  estimatedTRCount: number;
  complexity: string;
  priority: string;
  status: string;
  currentPhase: string;
  overallRAG: 'GREEN' | 'AMBER' | 'RED' | null;
  riskScore: number;
  deploymentPct: number;
  notes: string;
  sharepointSync: boolean;
  lastSynced: string;
  transports?: Transport[];
  milestones?: Milestone[];
}

// ─── Milestone Types ───
export interface Milestone {
  ID: string;
  workItem_ID: string;
  milestoneName: string;
  milestoneDate: string;
  milestoneOrder: number;
  status: 'Pending' | 'Complete' | 'Overdue';
  completedDate: string | null;
  autoGenerated: boolean;
  evidence: string;
}

// ─── Dashboard Summary ───
export interface DashboardSummary {
  activeProjects: number;
  totalTransports: number;
  unassignedCount: number;
  pendingItems: number;
  completedThisWeek: number;
  stuckTransports: number;
  failedImports: number;
  avgDeploymentDays: number;
}

// ─── Pipeline Summary ───
export interface PipelineSummary {
  devCount: number;
  qasCount: number;
  prdCount: number;
  queueCount: number;
  stuckCount: number;
  failedCount: number;
}

// ─── Health Status ───
export interface HealthStatus {
  status: string;
  database: string;
  rfc: string;
  sharepoint: string;
  timestamp: string;
}

// ─── Notification ───
export interface Notification {
  ID: string;
  userEmail: string;
  type: string;
  message: string;
  trNumber: string;
  isRead: boolean;
  createdAt: string;
}

// ─── User Roles ───
export type UserRole = 'Executive' | 'Manager' | 'Developer';

export interface UserInfo {
  email: string;
  name: string;
  roles: UserRole[];
}

// ─── API Response Wrappers ───
export interface ODataResponse<T> {
  value: T[];
}

export interface ActionResult {
  success: boolean;
  message: string;
}

export interface CategorizeResult extends ActionResult {}

export interface BulkCategorizeResult extends ActionResult {
  count: number;
}

export interface RefreshResult extends ActionResult {
  recordsFetched?: number;
  recordsSynced?: number;
}

export interface ReportResult extends ActionResult {
  report: string | null;
}
